Algoritmo "OPÇÃO ESCOLHA, PARA GUARDAR"

Var

VARIAVEL : inteiro
VARIAVEL2 : inteiro

Inicio

leia(VARIAVEL)

escolha VARIAVEL
caso 1
     VARIAVEL2 <- ALGO
caso 2
     VARIAVEL2 <- ALGO
caso 3
     VARIAVEL2 <- ALGO	
caso 4
     VARIAVEL2 <- ALGO
caso 5
     VARIAVEL2 <- ALGO
caso 6
     VARIAVEL2 <- ALGO
caso7
     VARIAVEL2 <- ALGO
outrocaso
         VARIAVEL2 <- ALGO DIFERENTE
fimescolha



Fimalgoritmo